# Extra autostart processes
exec-once = uwsm app -- cursor
exec-once = uwsm app -- gitkraken
# TODO: Replace ghostty with the default terminal whatever it is
exec-once = uwsm app -- ghostty
exec-once = uwsm app -- firefox
# TODO: Fix
# exec-once = uwsm app -- chromium
exec-once = sleep 2 && uwsm app -- slack
exec-once = sleep 3 && uwsm app -- Telegram
# exec-once = sleep 1 && uwsm app -- onedrivegui
exec-once = uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://web.whatsapp.com/" --name="WhatsApp" --class="WhatsApp"
exec-once = uwsm app -- chromium --new-window --ozone-platform=wayland --app="https://workflowy.com/" --name="Workflowy" --class="Workflowy"
