# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

windowrule = workspace `, match:initial_class cursor
windowrule = workspace 1, match:class GitKraken
windowrule = workspace 2, match:class firefox
# TODO: Bind clean Chromium instances to workspace 3
windowrule = workspace 4, match:class Slack
windowrule = workspace 4, match:class org.telegram.desktop
windowrule = workspace 4, match:class ^(.*chrome-web.whatsapp.com.*)$
windowrule = workspace 4, match:class ^(.*chrome-discord.com.*)$
windowrule = workspace 5, match:class ^(.*chrome-figma.com.*)$
windowrule = workspace 5, match:class ^(.*chrome-podcasts.apple.com.*)$
windowrule = workspace 5, match:class spotify
windowrule = workspace 5, match:class org.strawberrymusicplayer.strawberry
windowrule = workspace 5, match:class steam
windowrule = workspace 6, match:class org.gnome.Nautilus
windowrule = workspace 6, match:class ^(.*chrome-workflowy.com.*)$
windowrule = workspace 6, match:class OneDriveGUI

windowrule {
    name = telegram_fix
    match:class = org.telegram.desktop
    suppress_event = fullscreen maximize
}
